set -g default-shell /bin/zsh
set -g default-terminal "tmux-256color"
bind -n M-s copy-mode \; send-keys ?
bind s choose-tree -Zs -O name

setw -g mode-keys vi
set -g status-keys vi
set -g status-left-length 50

# change default key binding
# ref: tmux list-keys

bind-key -T copy-mode-vi 'v' send -X begin-selection     # Begin selection in copy mode.
bind-key -T copy-mode-vi 'C-v' send -X rectangle-toggle  # Begin selection in copy mode.

bind-key    -T copy-mode-vi    'j' send -X cursor-down
bind-key    -T copy-mode-vi    'k' send -X cursor-up
bind-key    -T copy-mode-vi    'h' send -X cursor-left
bind-key    -T copy-mode-vi    'l' send -X cursor-right

bind-key -T copy-mode-vi J send-keys -X page-down
bind-key -T copy-mode-vi K send-keys -X page-up

# update current session root directory
bind -n M-u attach-session -c '#{pane_current_path}'

# disable tmux-navigator
# in favor of csvlens left right navigation
# set -g @plugin 'christoomey/vim-tmux-navigator'
unbind -n C-l
unbind -n C-h

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'laktak/extrakto'
set -g @plugin 'omerxx/tmux-sessionx'

set -g @continuum-restore 'on'
set -g @resurrect-strategy-nvim 'session'
set -g @resurrect-strategy-vim 'session'
set -g @resurrect-capture-pane-contents 'on'
set -g @sessionx-bind 'o'
set -g @extrakto_filter_order "all word line"

# customize pop-up
bind-key T display-popup -w 80% -h 80% -E 'tmux new-session -A -s popup_shell $SHELL' 
bind-key C display-popup -w 80% -h 80% -E 'nvim ~/.tmux.conf'
bind-key N display-popup -w 80% -h 80% -E 'tmux new-session -A -s popup_note "nvim ~/note.md"'
bind-key E display-popup -w 90% -h 90% -E -d '#{pane_current_path}' 'ranger'
bind-key G display-popup -w 90% -h 90% -E -d '#{pane_current_path}' 'codex'
bind-key D display-popup -w 90% -h 90% -E 'tmux new-session -A -s popup_db "nvim -c DBUI"'
bind-key P display-popup -w 90% -h 90% -E 'tmux new-session -A -s popup_nvim -c ~/adhoc "nvim ~/adhoc/bin/playground.py"'

# leader C-I to install
# leader M-u to uninstall


# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

