set -g default-shell /bin/zsh
set -g default-terminal "tmux-256color"
bind -n M-s copy-mode \; send-keys ?
bind s choose-tree -Zs -O name

setw -g mode-keys vi
set -g status-keys vi

# change default key binding
# ref: tmux list-keys

bind-key -T copy-mode-vi 'v' send -X begin-selection     # Begin selection in copy mode.
bind-key -T copy-mode-vi 'C-v' send -X rectangle-toggle  # Begin selection in copy mode.

bind-key    -T copy-mode-vi    'j' send -X cursor-down
bind-key    -T copy-mode-vi    'k' send -X cursor-up
bind-key    -T copy-mode-vi    'h' send -X cursor-left
bind-key    -T copy-mode-vi    'l' send -X cursor-right

bind-key -T copy-mode-vi J send-keys -X page-down
bind-key -T copy-mode-vi K send-keys -X page-up

# update current session root directory
bind -n M-u attach-session -c '#{pane_current_path}'

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-yank'

set -g @continuum-restore 'on'
set -g @resurrect-strategy-nvim 'session'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

